### ISSUE TITLE
phxsql无法运行，启动时有core

### ISSUE THREAD

**Issue by chenxiyu1204** [Tencent/phxsql#163]
[root@localhost sbin]# gdb -f phxbinlogsvr_tools_phxrpc -c core.124118 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/phxsql/sbin/phxbinlogsvr_tools_phxrpc...done.

warning: core file may not match specified executable file.
[New LWP 124118]
Core was generated by `./phxbinlogsvr_tools_phxrpc -f InitBinlogSvrMaster -h192.168.XX.XXX,192.168.XX.'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000005c7243 in std::__throw_system_error(int) ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64
(gdb) bt
#0  0x00000000005c7243 in std::__throw_system_error(int) ()
#1  0x0000000000424aae in std::call_once<void (&)()> (__once=..., __f=@0x4175c2: {void (void)} 0x4175c2 <protobuf_phxbinlogsvr_2eproto::AddDescriptorsImpl()>) at /usr/include/c++/4.8.2/mutex:794
#2  0x00000000004241e2 in google::protobuf::internal::call_once<std::once_flag&, void (&)()> () at /phxsql/phxsql-master/third_party/protobuf/include/google/protobuf/stubs/once.h:91
#3  0x000000000041761d in protobuf_phxbinlogsvr_2eproto::AddDescriptors () at phxbinlogsvr.pb.cc:398
#4  0x0000000000423d93 in protobuf_phxbinlogsvr_2eproto::StaticDescriptorInitializer::StaticDescriptorInitializer (this=0x8c3588 <protobuf_phxbinlogsvr_2eproto::static_descriptor_initializer>)
    at phxbinlogsvr.pb.cc:403
#5  0x0000000000421d7c in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at phxbinlogsvr.pb.cc:405
#6  0x0000000000421eb9 in _GLOBAL__sub_I_phxbinlogsvr.pb.cc(void) () at phxbinlogsvr.pb.cc:3119
#7  0x00000000005e578d in __libc_csu_init ()
#8  0x00007f1dfed8f3d5 in __libc_start_main () from /lib64/libc.so.6
#9  0x0000000000404027 in _start ()

请帮忙看看是什么原因？

**Comment by taohexxx** [comment]
你好，可能是你使用的phxsql与phxrpc版本不兼容引起的，目前有两种使用方式：1. 稳定版：用phxsql的release最新版压缩包，配合使用phxrpc的release最新版压缩包；2. 开发版：用phxsql的master分支最新代码，配合使用phxrpc的master分支最新代码。

**Comment by chenxiyu1204** [comment]
按方法1、重新获取了两个安装包，问题还是存在。  是否是protobuf需要指定版本？

**Comment by taohexxx** [comment]
protobuf不需要指定版本
